server:
  prefixurl: localhost:8080
  runmode: debug
  httpport: 8080
  runtimerootpath: runtime/
  readtimeout: 60
  writetimeout: 60
  timeformat: 20060102
database:
  type: mysql
  connections:
    default: root:123456@tcp(127.0.0.1:3306)/gomall?charset=utf8&parseTime=True&loc=Local
    yaoxieda: root:123456@tcp(127.0.0.1:3306)/yaoxieda?charset=utf8&parseTime=True&loc=Local
    # mcjie: root:123456@tcp(127.0.0.1:3306)/yaoxieda?charset=utf8&parseTime=True&loc=Local

redis:
  default:
    addr: 127.0.0.1:6379
    db: 0
  yaoxieda:
    addr: 127.0.0.1:6379
    db: 1

logger:
  logsavepath: logs/
  logsavename: gomall
  logfileext: log
auth:
  jwtsecret: token-secret
  expiretime: 24 # hour
pagger:
  pagesize: 20
media:
  imagesavepath: upload/images/
  imagemaxsize: 5 # 5M
  imageallowexts: [.jpg, .png]
  qrcodesavepath: qrcode/
